# This file is a template, and might need editing before it works on your project.
# Official Java image. Look for the different tagged releases at
# https://hub.docker.com/r/library/java/tags/ . A Java image is not required
# but an image with a JVM speeds up the build a bit.
image: openjdk:8

before_script:
  # Enable the usage of sources over https
  - apt-get update -yqq
  - apt-get install apt-transport-https -yqq
  # Add keyserver for SBT
  - wget https://piccolo.link/sbt-1.3.0.tgz
  - tar zxvf sbt-1.3.0.tgz
  # Install SBT
   # Log the sbt version
  - ./sbt/bin/sbt sbt-version

test:
  script:
    # Execute your project's tests
    - ./sbt/bin/sbt  clean test
